language: node_js
node_js:
  - "16"

services:
  - docker

before_install:
  - docker build -t pete-rk/docker-react -f Dockerfile.dev .

script:
  - docker run pete-rk/docker-react npm run test -- --coverage
