language: node_js
node_js:
  - "16"

sudo: required
servides:
  - docker

before_install:
  - docker build -t pete-RK/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pete-RK/docker-react npm run test
